### ISSUE TITLE
ViT-B/32 models?

### ISSUE THREAD

**Issue by vishaal27** [LijieFan/LaCLIP#1]
Hi, thanks for your great work and open-source code and models. Are you planning to release the ViT-B/32 models trained on LAION-400M?

**Comment by HobbitLong** [comment]
Yes, we will. 

Because we used different codebase for training on LAION-400M (used OpenCLIP) and the others, we need slightly more work to clean and release the model for LAION-400M.

**Comment by LijieFan** [comment]
Just updated the link and eval code for LAION-400 models!

**Comment by vishaal27** [comment]
Great, thanks for your prompt response!
