### ISSUE TITLE
pt_load

### ISSUE THREAD

**Issue by bumi001** [LijieFan/LaCLIP#2]
Hi, Thank you for sharing this work. In eval_zeroshot_imagenet_laion.py I commented out lines related to pt_load and replaced the call to pt_load with the code for loading the checkpoint from eval_zeroshot_imagenet.py and it works.

--Comment these lines
from training.file_utils import pt_load
checkpoint = pt_load(args.ckpt_path, map_location='cpu')

--Add these lines
ckpt_path = args.ckpt_path
ckpt = torch.load(ckpt_path, map_location='cpu')

state_dict = OrderedDict()
for k, v in ckpt['state_dict'].items():
    state_dict[k.replace('module.', '')] = v

model.load_state_dict(state_dict, strict=True)

**Comment by LijieFan** [comment]
Thank you for the comments, we've fixed the loading issue in the recent update
