### ISSUE TITLE
Performance on Downstream Tasks

### ISSUE THREAD

**Issue by praeclarumjj3** [LijieFan/LaCLIP#4]
Hi, thanks for the great work!

I wonder how much improvement LaCLIP demonstrates on downstream tasks like zero-shot image understanding (segmentation, detection, etc.), where the community has widely leveraged CLIP. Did you perform any experiments along these lines?

Thanks!

**Comment by HobbitLong** [comment]
Hi, @praeclarumjj3,

We haven't tried zero-shot segmentation or detection, as it's out of the scope of this paper. But I am also wondering how it would perform.
