### ISSUE TITLE
Unable to reproduce CLIP Baselines on CC3M with original captions

### ISSUE THREAD

**Issue by HaniItani** [LijieFan/LaCLIP#6]
Hello,

Thank you for sharing your great work!

I'm having issues reproducing your CLIP baselines for CC3M using the original captions. I suspect you are using the SLIP codebase to train your models for CC3M and CC12M, and I'm doing the same. I also noticed that the difference between your CLIP implementation and theirs is the qk_norm in the attention blocks in the vision transformer.

I've implemented your evaluation pipeline and managed to reproduce the linear probing numbers you report for some of the datasets using your provided checkpoint. You can see that the gap between my reproduction attempt and yours is substantial. Note that best ImageNet zero shot I got in my reproduction is 15.2 which is comparable to your reported 15.8.

![image](https://github.com/LijieFan/LaCLIP/assets/41548851/6c4d16c8-d297-4bf9-9c5e-3faa03275932)

Can you please advise? Thanks!

**Comment by HobbitLong** [comment]
Hi, @HaniItani,

Yes, we modify from SLIP repo. However, their all_gather operator doesn't have gradient back-propagation, you need to switch to another one that have gradient back-propagation, e.g. `torch.distributed.nn.all_gather`.

Yes, we used qk_norm. Our initial trial shows it improves the training stability a bit so we kept it. Performance-wise, I don't think it caused noticeable differences.

For the linear probing, we followed the setup in, e.g., section A.6 of this [paper](https://arxiv.org/pdf/2306.00984.pdf).

**Comment by HaniItani** [comment]
Hi @HobbitLong,

Thank you very much for your response. Can you please elaborate on this fix? Is it as easy as replacing this line [here](https://github.com/facebookresearch/SLIP/blob/c6faf5d03cbfa7d529d210779f859cd3dddec09a/utils.py#L136) with torch.distributed.nn.all_gather? I also see SLIP code base has gather with grad function [here](https://github.com/facebookresearch/SLIP/blob/c6faf5d03cbfa7d529d210779f859cd3dddec09a/utils.py#L168). Is it the same?

Your reply is very much appreciated.

**Comment by LijieFan** [comment]
Hi @HaniItani ,
Thanks again for your interest, please refer to our [loss implementation](https://github.com/LijieFan/LaCLIP/blob/7ddd516e7a2b94651a819217b573b157b461199d/losses.py#L31)
